"""create_telegram_channels_table

Revision ID: 3c7f960e9681
Revises: 001_telegram_messages
Create Date: 2026-01-14 01:24:26.176909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7f960e9681'
down_revision: Union[str, Sequence[str], None] = '001_telegram_messages'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_channels_channel_id'), 'telegram_channels', ['channel_id'], unique=True)
    op.create_index(op.f('ix_telegram_channels_id'), 'telegram_channels', ['id'], unique=False)
    op.drop_index(op.f('ix_ingestion_sources_id'), table_name='ingestion_sources')
    op.drop_table('ingestion_sources')
    op.drop_index(op.f('ix_scheduled_ingestions_id'), table_name='scheduled_ingestions')
    op.drop_table('scheduled_ingestions')
    op.drop_index(op.f('ix_symbol_upload_logs_id'), table_name='symbol_upload_logs')
    op.drop_table('symbol_upload_logs')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_symbols_exchange'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_trading_symbol'), table_name='symbols')
    op.drop_table('symbols')
    op.alter_column('access_requests', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('access_requests', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_access_requests_mobile'), 'access_requests', ['mobile'], unique=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_telegram_messages_assigned_to'), table_name='telegram_messages')
    op.drop_column('telegram_messages', 'claimed_at')
    op.drop_column('telegram_messages', 'assigned_to')
    op.drop_column('telegram_messages', 'status')
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'account_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))
    op.alter_column('users', 'theme_preference',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'dark'"))
    op.alter_column('users', 'last_active_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'telegram_chat_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.alter_column('users', 'telegram_chat_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'last_active_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'theme_preference',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'dark'"))
    op.alter_column('users', 'account_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'"))
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('telegram_messages', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'open'"), nullable=False))
    op.add_column('telegram_messages', sa.Column('assigned_to', sa.INTEGER(), nullable=True))
    op.add_column('telegram_messages', sa.Column('claimed_at', sa.TIMESTAMP(), nullable=True))
    op.create_index(op.f('ix_telegram_messages_assigned_to'), 'telegram_messages', ['assigned_to'], unique=False)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_access_requests_mobile'), table_name='access_requests')
    op.alter_column('access_requests', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('access_requests', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('symbols',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exchange', sa.VARCHAR(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('trading_symbol', sa.VARCHAR(), nullable=False),
    sa.Column('instrument_type', sa.VARCHAR(), nullable=False),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('strike_price', sa.FLOAT(), nullable=True),
    sa.Column('option_type', sa.VARCHAR(), nullable=True),
    sa.Column('lot_size', sa.INTEGER(), nullable=True),
    sa.Column('tick_size', sa.FLOAT(), nullable=True),
    sa.Column('isin', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('exchange_token', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('segment', sa.TEXT(), nullable=True),
    sa.Column('series', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_trading_symbol'), 'symbols', ['trading_symbol'], unique=1)
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=False)
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_index(op.f('ix_symbols_exchange'), 'symbols', ['exchange'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_activity', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=1)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('symbol_upload_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('upload_type', sa.VARCHAR(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('record_count', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('errors', sa.TEXT(), nullable=True),
    sa.Column('script_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['transformation_scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_upload_logs_id'), 'symbol_upload_logs', ['id'], unique=False)
    op.create_table('scheduled_ingestions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('mode', sa.VARCHAR(), nullable=False),
    sa.Column('interval_value', sa.INTEGER(), nullable=True),
    sa.Column('interval_unit', sa.VARCHAR(), nullable=True),
    sa.Column('cron_expression', sa.VARCHAR(), nullable=True),
    sa.Column('script_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('last_run_at', sa.DATETIME(), nullable=True),
    sa.Column('next_run_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['transformation_scripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_scheduled_ingestions_id'), 'scheduled_ingestions', ['id'], unique=False)
    op.create_table('ingestion_sources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scheduler_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('source_type', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('headers', sa.TEXT(), nullable=True),
    sa.Column('auth_type', sa.VARCHAR(), nullable=True),
    sa.Column('auth_value', sa.VARCHAR(), nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('last_run_at', sa.DATETIME(), nullable=True),
    sa.Column('last_status', sa.VARCHAR(), nullable=True),
    sa.Column('last_error', sa.TEXT(), nullable=True),
    sa.Column('last_record_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['scheduler_id'], ['scheduled_ingestions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_sources_id'), 'ingestion_sources', ['id'], unique=False)
    op.drop_index(op.f('ix_telegram_channels_id'), table_name='telegram_channels')
    op.drop_index(op.f('ix_telegram_channels_channel_id'), table_name='telegram_channels')
    op.drop_table('telegram_channels')
    # ### end Alembic commands ###
